[package]
name = "imsearch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
opencv = "0.54"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rusqlite = "0.25"
structopt = "0.3.23"
walkdir = "2.3.2"

[build-dependencies]
cc = "1.0.70"
pkg-config = "0.3.19"
