[package]
name = "imsearch"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
directories = "5.0.1"
fdlimit = "0.2.1"
num_cpus = "1.16.0"
once_cell = "1.18.0"
opencv = { version = "0.83.0", features = ["clang-runtime"] }
rayon = "1.7.0"
regex = "1.9.1"
serde_json = "1.0.104"
structopt = "0.3.26"
walkdir = "2.3.3"
itertools = "0.11.0"
env_logger = "0.10.0"
log = "0.4.19"
dashmap = "5.5.0"
crossbeam-utils = "0.8.16"
libc = "0.2.147"
blake3 = "1.4.1"
rouille = "3.6.2"
tempfile = "3.7.0"
ndarray = "0.15.6"
ndarray-npy = "0.8.1"

[dependencies.rocksdb]
version = "0.21.0"
default-features = false
features = ["lz4", "zstd", "multi-threaded-cf"]

[build-dependencies]
cc = "1.0.80"
dunce = "1.0.4"
glob = "0.3.1"
once_cell = "1.18.0"
pkg-config = "0.3.27"
semver = "1.0.18"
shlex = "1.1.0"
vcpkg = "0.2.15"
