[package]
name = "imsearch"
version = "2.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
axum = { version = "0.8.3", features = ["multipart", "macros"] }
axum_typed_multipart = { version = "0.16.0", default-features = false }
blake3 = "1.8.2"
clap = { version = "4.5.37", features = ["derive"] }
directories = "6.0.0"
env_logger = "0.11.8"
futures = "0.3.31"
indicatif = { version = "0.17.11", features = ["rayon"] }
log = "0.4.27"
ndarray = "0.16.1"
ndarray-npy = "0.9.1"
num_cpus = "1.16.0"
rayon = "1.10.0"
regex = "1.11.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.5", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "rt"] }
tower-http = { version = "0.5.2", features = ["limit"] }
utoipa = { version = "5.3.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.1", features = ["axum"] }
walkdir = "2.5.0"

[dependencies.faiss-sys]
version = "0.6.3-alpha.0"
git = "https://github.com/Aloxaf/faiss-rs"
branch = "imsearch"
features = ["static", "avx2"]

[dependencies.opencv]
version = "0.94.4"
default-features = false
features = [
    "clang-runtime",
    "highgui",
    "features2d",
    "flann",
    "imgcodecs",
    "imgproc",
]

[dependencies.rocksdb]
optional = true
version = "0.21.0"
default-features = false
features = ["lz4", "zstd", "multi-threaded-cf"]

[features]
default = []
rocksdb = ["dep:rocksdb"]

[build-dependencies]
cc = "1.2.19"
dunce = "1.0.5"
glob = "0.3.2"
pkg-config = "0.3.32"
semver = "1.0.26"
shlex = "1.3.0"
vcpkg = "0.2.15"
