[package]
name = "imsearch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
directories = "3.0.2"
num_cpus = "1.13.0"
once_cell = "1.8.0"
opencv = "0.54"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rayon = "1.5.1"
regex = "1.5.4"
rusqlite = "0.25"
serde_json = "1.0.67"
structopt = "0.3.23"
walkdir = "2.3.2"

[build-dependencies]
cc = "1.0.70"
dunce = "1.0.2"
glob = "0.3.0"
once_cell = "1.8.0"
pkg-config = "0.3.19"
semver = "1.0.4"
shlex = "1.1.0"
vcpkg = "0.2.9"
